# Generated by Django 4.2.4 on 2024-09-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('Cybersecurity', 'Cybersecurity'), ('Web Development', 'Web Development'), ('Cloud Computing', 'Cloud Computing'), ('Blockchain', 'Blockchain'), ('DevOps', 'DevOps'), ('Networking', 'Networking'), ('Software Engineering', 'Software Engineering')], max_length=50),
        ),
    ]
